#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use C4::Auth qw/check_api_auth/;
use C4::Members;
use C4::Reserves;
use Koha::Patrons;
use XML::Simple;

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}
my $userid= $query->url_param('borrower');
#my $borrower = GetMember(userid => $userid);
my $patrons = Koha::Patrons->search({userid => $userid});
my $borrower = $patrons->next;
unless ($borrower) {
  print $query->header(-type => 'text/xml', -status => '404 Not found');
  print XMLout({ status => 'Borrower not found', error_code => 'borrowerNotFound' }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my $flags = C4::Members::patronflags($borrower->unblessed);
my $borrowernumber = $borrower->unblessed->{'borrowernumber'};
my $issues = C4::Members::GetAllIssues($borrowernumber);
my @reserves = $borrower->holds->unblessed;

print $query->header(-type => 'text/xml',-charset => 'utf-8');

print XMLout({ 
flags => $flags, 
borrower => $borrower->unblessed, 
issues => $issues, 
reserves => \@reserves }, NoAttr => 1, RootName => 'response', XMLDecl => 1);

exit 0;
