#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use XML::Simple;
use C4::Auth qw/check_api_auth/;

use C4::Reserves;

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my $reserve_id = $query->param('reserve_id');
my $reserve = Koha::Holds->find($reserve_id)->unblessed;

unless ($reserve) {
  print $query->header(-type => 'text/xml', -status => '404');
  print XMLout({ status => "Reserve not found", error_code => "reserveNotFound"  }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

C4::Reserves::CancelReserve({ reserve_id => $reserve_id });

print $query->header(-type => 'text/xml',-charset => 'utf-8', -status => '200');
exit 0;
