version: '3.7'
services:
  frontend:
    image: docker.ub.gu.se/bestall-frontend:${GIT_REVISION}
    ports:
      - ${FRONTEND_HOST_PORT}:8080
  backend:
    image: docker.ub.gu.se/bestall-backend:${GIT_REVISION}
  db:
    image: docker.ub.gu.se/bestall-postgres:${GIT_REVISION}
  apache:
    image: ${BESTALL_APACHE_RUNNING_IMAGE} 
    restart: always
    ports:
      - ${BESTALL_APACHE_ACCESS_PORT}:80
    volumes:
      - "${BESTALL_APACHE_SITES_DIR}:/etc/apache2/sites-enabled"
      - "${FILES_DIR}:/var/www/bestall/files"
      - "${PRINT_BESTALL_DIR}:/var/www/bestall/print_bestall"
      - "${BESTALL_APACHE_HTPASSWD_DIR}:/etc/htpasswd/bestall"
  cupsd:
    image: ${BESTALL_CUPSD_RUNNING_IMAGE} 
    restart: always
    environment:
      - PRINTER_PR40_URI=${PRINTER_PR40_URI}
      - PRINTER_PR42_URI=${PRINTER_PR42_URI}
      - PRINTER_PR43_URI=${PRINTER_PR43_URI}
      - PRINTER_PR44_URI=${PRINTER_PR44_URI}
      - PRINTER_PR47_URI=${PRINTER_PR47_URI}
      - PRINTER_PR48_URI=${PRINTER_PR48_URI}
      - PRINTER_PR49_URI=${PRINTER_PR49_URI}
      - PRINTER_PR50_URI=${PRINTER_PR50_URI}
      - PRINTER_PR60_URI=${PRINTER_PR60_URI}
      - PRINTER_PR62_URI=${PRINTER_PR62_URI}
      - PRINTER_TEST_URI=${PRINTER_TEST_URI}
    volumes:
      - "${FILES_DIR}:/apps/bestall/files"

