version: "3.7"
name: bestall
services:
  frontend:
    env_file:
      - secrets.env
    environment:
      - EMBER_ENVIRONMENT=${ENVIRONMENT}
      - GUB_OAUTH2_CLIENT_ID=${GUB_OAUTH2_CLIENT_ID}
      - GUB_OAUTH2_AUTHORIZE_ENDPOINT=${GUB_OAUTH2_AUTHORIZE_ENDPOINT}
      - PIN_CODE_ACTIVE=${PIN_CODE_ACTIVE}
      - PIN_CODE_FORGOT_LINK_SV=${PIN_CODE_FORGOT_LINK_SV}
      - PIN_CODE_FORGOT_LINK_EN=${PIN_CODE_FORGOT_LINK_EN}
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    tty: true
    restart: always
  backend:
    restart: always
    env_file:
      - secrets.env
    environment:
      - RAILS_ENV=${ENVIRONMENT}
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_PORT=${RAILS_PORT}
      - RAILS_DB=${DB_NAME}
      - RAILS_DB_HOST=${DB_HOST}
      - RAILS_DB_USER=${DB_USER}
      - RAILS_DB_PASSWORD=${DB_PASSWORD}
      - BESTALL_REGISTRATION_URL=${REGISTRATION_URL}
      - BESTALL_MYLOANS_URL=${MYLOANS_URL}
      - BESTALL_KOHA_USER=${KOHA_USER}
      - BESTALL_KOHA_SVC_URL=${KOHA_SVC_URL}
      - BESTALL_KOHA_SVC_AUTH_URL=${KOHA_SVC_AUTH_URL}
      - SHOW_PICKUP_CODE=${SHOW_PICKUP_CODE}
      - GUB_OAUTH2_PROVIDER=${GUB_OAUTH2_PROVIDER}
      - GUB_OAUTH2_CLIENT_ID=${GUB_OAUTH2_CLIENT_ID}
      - GUB_OAUTH2_TOKEN_ENDPOINT=${GUB_OAUTH2_TOKEN_ENDPOINT}
      - GUB_OAUTH2_USER_ENDPOINT=${GUB_OAUTH2_USER_ENDPOINT}
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    networks:
      - backend
    ports:
      - ${BACKEND_HOST_PORT}:${RAILS_PORT}
  db:
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
