version: '3.7'
services:
  frontend:
    environment:
      - BACKEND_SERVICE_HOSTNAME=${BACKEND_HOSTNAME}
      - FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME}
    image: docker.ub.gu.se/bestall-frontend:${GIT_REVISION}
    ports:
      - ${FRONTEND_HOST_PORT}:8080
  backend:
    image: docker.ub.gu.se/bestall-backend:${GIT_REVISION}
    environment:
      - FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME}
    volumes:
      - "${BACKEND_DATA_HOST_DIR}:/usr/src/app/config/data"
      - ${FILES_HOST_DIR}:/opt/bestall-files
  db:
    image: docker.ub.gu.se/bestall-postgres:${GIT_REVISION}
  apache:
    image: docker.ub.gu.se/bestall-apache:${APACHE_GIT_REVISION}
    restart: always
    ports:
      - ${APACHE_HOST_PORT}:80
    volumes:
      - "${APACHE_SITES_HOST_DIR}:/etc/apache2/sites-enabled"
      - "${FILES_HOST_DIR}:/var/www/bestall/files"
  cupsd:
    image: docker.ub.gu.se/bestall-cupsd:${CUPSD_GIT_REVISION}
    restart: always
    environment:
      - PRINTER_PR40_URI=${PRINTER_PR40_URI}
      - PRINTER_PR42_URI=${PRINTER_PR42_URI}
      - PRINTER_PR43_URI=${PRINTER_PR43_URI}
      - PRINTER_PR44_URI=${PRINTER_PR44_URI}
      - PRINTER_PR47_URI=${PRINTER_PR47_URI}
      - PRINTER_PR48_URI=${PRINTER_PR48_URI}
      - PRINTER_PR49_URI=${PRINTER_PR49_URI}
      - PRINTER_PR50_URI=${PRINTER_PR50_URI}
      - PRINTER_PR60_URI=${PRINTER_PR60_URI}
      - PRINTER_PR62_URI=${PRINTER_PR62_URI}
      - PRINTER_TEST_URI=${PRINTER_TEST_URI}
    volumes:
      - "${FILES_HOST_DIR}:/apps/bestall/files"
  omutskrift:
    image: docker.ub.gu.se/bestall-omutskrift:${OMUTSKRIFT_GIT_REVISION}
    restart: always
    ports:
      - ${OMUTSKRIFT_HOST_PORT}:4000
    environment:
      - PRINT_DIR=${OMUTSKRIFT_PRINT_DIR}
      - PRINTED_DIR=${OMUTSKRIFT_PRINTED_DIR}
      - DOWNLOAD_ADDRESS=${OMUTSKRIFT_DOWNLOAD_ADDRESS}
      - DOWNLOAD_PATH=${OMUTSKRIFT_DOWNLOAD_PATH}
      - PROXY_PATH=${OMUTSKRIFT_PROXY_PATH}
    volumes:
      - "${FILES_HOST_DIR}:/data/files"
