services:
  name: bestall
  frontend:
    env_file:
      - secrets.env
    restart: always
    environment:
      - NUXT_PUBLIC_ENABLED_AUTH=${NUXT_ENABLED_AUTH}
      - NUXT_PUBLIC_HIDE_GU_AUTH_PARAM_NAME=${NUXT_HIDE_GU_AUTH_PARAM_NAME}
      - NUXT_PUBLIC_HIDE_GU_AUTH_PARAM_VALUE=${NUXT_HIDE_GU_AUTH_PARAM_VALUE}
      - NUXT_PUBLIC_LOCALE_PARAM_NAME=${NUXT_LOCALE_PARAM_NAME}
      - NUXT_PUBLIC_MYLOANS_URL=${NUXT_MYLOANS_URL}
      - NUXT_PUBLIC_DATE_FORMAT=${NUXT_DATE_FORMAT}
      - NUXT_PUBLIC_APPLICATION_IS_CLOSED=${NUXT_APPLICATION_IS_CLOSED}
      - NUXT_PUBLIC_DEBUG_INFO=${NUXT_DEBUG_INFO}
      - NUXT_PUBLIC_RESERVE_NOTE_MAX_LENGTH=${NUXT_RESERVE_NOTE_MAX_LENGTH}
      - NUXT_PUBLIC_GITHUB_CLIENT_ID=${NUXT_GITHUB_CLIENT_ID}
      - NUXT_PUBLIC_GU_CLIENT_ID=${GUB_OAUTH2_CLIENT_ID}
      - NUXT_PUBLIC_SHOW_AUTH_STATUS=${NUXT_PUBLIC_SHOW_AUTH_STATUS}
    stdin_open: true
    tty: true
    networks:
      - backend
  backend:
    restart: always
    env_file:
      - secrets.env
    environment:
      - RAILS_ENV=${ENVIRONMENT}
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_PORT=${RAILS_PORT}
      - BESTALL_REGISTRATION_URL=${REGISTRATION_URL}
      - BESTALL_MYLOANS_URL=${MYLOANS_URL}
      - BESTALL_KOHA_USER=${KOHA_USER}
      - BESTALL_KOHA_SVC_URL=${KOHA_SVC_URL}
      - BESTALL_KOHA_SVC_AUTH_URL=${KOHA_SVC_AUTH_URL}
      - SHOW_PICKUP_CODE=${SHOW_PICKUP_CODE}
      - GUB_OAUTH2_PROVIDER=${GUB_OAUTH2_PROVIDER}
      - GUB_OAUTH2_CLIENT_ID=${GUB_OAUTH2_CLIENT_ID}
      - GUB_OAUTH2_TOKEN_ENDPOINT=${GUB_OAUTH2_TOKEN_ENDPOINT}
      - GUB_OAUTH2_USER_ENDPOINT=${GUB_OAUTH2_USER_ENDPOINT}
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    networks:
      - backend
    ports:
      - ${BACKEND_HOST_PORT}:${RAILS_PORT}
networks:
  backend:
