#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use C4::Auth qw/check_api_auth/;
use XML::Simple;
use C4::Serials;

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my $biblionumber = $query->param('biblionumber');

unless ($biblionumber) {
  print $query->header(-type => 'text/xml', -status => '400');
  print XMLout({ status => "Biblionumber is required", error_code => 'biblionumberIsMissing' }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my $subscriptions = C4::Serials::GetSubscriptionsFromBiblionumber($biblionumber);

unless ($subscriptions) {
  print $query->header(-type => 'text/xml', -status => '500');
  print XMLout({ status => "Unrecognized error", error_code => 'unrecognizedError' }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

print $query->header(-type => 'text/xml',-charset => 'utf-8');
print XMLout({subscriptions => $subscriptions}, NoAttr => 1, RootName => 'response', XMLDecl => 1);

exit 0;
