cas_url: <%= ENV["BESTALL_CAS_URL"] ? ENV["BESTALL_CAS_URL"] : 'https://idp3.it.gu.se/idp/profile/cas' %>
registration_url: <%= ENV["BESTALL_REGISTRATION_URL"] %>
myloans_url: <%= ENV["BESTALL_MYLOANS_URL"] %>
koha:
  base_url: <%= ENV["BESTALL_KOHA_SVC_URL"] %>
  user: <%= ENV["BESTALL_KOHA_USER"] %>
  password: <%= ENV["KOHA_PASSWORD"] %>
file_path: /opt/bestall-files
api_key: <%= ENV["BESTALL_API_KEY"] %>
cache:
  api_key: <%= ENV["BESTALL_CACHE_API_KEY"] %>
show_pickup_code: <%= ENV["SHOW_PICKUP_CODE"] %>
oauth2:
  provider: <%= ENV["GUB_OAUTH2_PROVIDER"] %>
  client_id: <%= ENV["GUB_OAUTH2_CLIENT_ID"] %>
  client_secret: <%= ENV["GUB_OAUTH2_CLIENT_SECRET"] %>
  token_endpoint: <%= ENV["GUB_OAUTH2_TOKEN_ENDPOINT"] %>
  user_endpoint: <%= ENV["GUB_OAUTH2_USER_ENDPOINT"] %>
