cas_url: <%= ENV["BESTALL_CAS_URL"] ? ENV["BESTALL_CAS_URL"] : 'https://idp3.it.gu.se/idp/profile/cas' %>
registration_url: <%= ENV["BESTALL_REGISTRATION_URL"] %>
myloans_url: <%= ENV["BESTALL_MYLOANS_URL"] %>

koha:
  base_url: <%= ENV["BESTALL_KOHA_SVC_URL"] %>
  user: <%= ENV["BESTALL_KOHA_USER"] %>
  password: <%= ENV["KOHA_PASSWORD"] %>
file_path: /opt/bestall-files
api_key: <%= ENV["BESTALL_API_KEY"] %>
